name: developercontrol
description: Streamline enabling Developer Options and USB Debugging on non-rooted Android devices.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/logo/logo.png
    - assets/screenshots/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/logo/logo.png
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: assets/logo/logo.png
  min_sdk_android: 24
